name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # o la rama que desees usar

jobs:
  name: Deploy
  runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      uses: actions/checkout@v2


    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


